# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.com_port_CB = QtWidgets.QComboBox(self.centralwidget)
        self.com_port_CB.setGeometry(QtCore.QRect(20, 30, 150, 31))
        self.com_port_CB.setMinimumSize(QtCore.QSize(150, 30))
        self.com_port_CB.setObjectName("com_port_CB")
        self.connect_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.connect_BTN.setGeometry(QtCore.QRect(20, 80, 150, 30))
        self.connect_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.connect_BTN.setObjectName("connect_BTN")
        self.read_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.read_BTN.setGeometry(QtCore.QRect(20, 190, 150, 30))
        self.read_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.read_BTN.setObjectName("read_BTN")
        self.stop_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.stop_BTN.setGeometry(QtCore.QRect(20, 240, 150, 30))
        self.stop_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.stop_BTN.setObjectName("stop_BTN")
        self.read_nastr_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.read_nastr_BTN.setGeometry(QtCore.QRect(20, 130, 150, 30))
        self.read_nastr_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.read_nastr_BTN.setObjectName("read_nastr_BTN")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(180, 20, 250, 511))
        self.tableWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(125)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_BTN.setText(_translate("MainWindow", "Подключиться"))
        self.read_BTN.setText(_translate("MainWindow", "Читать"))
        self.stop_BTN.setText(_translate("MainWindow", "Остановить"))
        self.read_nastr_BTN.setText(_translate("MainWindow", "Читать настройки"))


class WriteWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(WriteWindow, self).__init__()
        self.initUi()

    def initUi(self):
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 250, 30))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.value_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.value_LE.setGeometry(QtCore.QRect(10, 60, 250, 30))
        self.value_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.value_LE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.value_LE.setText("")
        self.value_LE.setObjectName("value_LE")
        self.write_value_btn = QtWidgets.QPushButton(self.centralwidget)
        self.write_value_btn.setGeometry(QtCore.QRect(10, 110, 75, 30))
        self.write_value_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.write_value_btn.setText('Записать')
        self.write_value_btn.setObjectName("write_value_btn")
        self.cancel_value_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_value_btn.setGeometry(QtCore.QRect(185, 110, 75, 30))
        self.cancel_value_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.cancel_value_btn.setText('Отмена')
        self.cancel_value_btn.setObjectName("cancel_value_btn")
        self.setCentralWidget(self.centralwidget)
        self.resize(270, 160)
