# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.com_port_CB = QtWidgets.QComboBox(self.centralwidget)
        self.com_port_CB.setGeometry(QtCore.QRect(20, 30, 150, 31))
        self.com_port_CB.setMinimumSize(QtCore.QSize(150, 30))
        self.com_port_CB.setObjectName("com_port_CB")
        self.connect_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.connect_BTN.setGeometry(QtCore.QRect(20, 80, 150, 30))
        self.connect_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.connect_BTN.setObjectName("connect_BTN")
        self.read_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.read_BTN.setGeometry(QtCore.QRect(20, 190, 150, 30))
        self.read_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.read_BTN.setObjectName("read_BTN")
        self.stop_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.stop_BTN.setGeometry(QtCore.QRect(20, 240, 150, 30))
        self.stop_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.stop_BTN.setObjectName("stop_BTN")
        self.read_nastr_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.read_nastr_BTN.setGeometry(QtCore.QRect(20, 130, 150, 30))
        self.read_nastr_BTN.setMinimumSize(QtCore.QSize(150, 30))
        self.read_nastr_BTN.setObjectName("read_nastr_BTN")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(180, 20, 250, 511))
        self.tableWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(125)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_BTN.setText(_translate("MainWindow", "Подключиться"))
        self.read_BTN.setText(_translate("MainWindow", "Читать"))
        self.stop_BTN.setText(_translate("MainWindow", "Остановить"))
        self.read_nastr_BTN.setText(_translate("MainWindow", "Читать настройки"))
